import Image from 'next/image'

/**
 * Pencil-drawn farm (the Mr Dairy "etched farm" look): hills, tree line, barn,
 * silo, trees, fence and sketches of our own cows. The artwork is generated by
 * scripts/farm-sketch.py; it is anchored to the bottom and cropped to fit.
 */
export function FarmSketch({ className = '', imgClassName = 'object-[18%_100%] md:object-bottom' }: { className?: string; imgClassName?: string; count?: number }) {
  return (
    <div className={`pointer-events-none ${/\babsolute\b/.test(className) ? '' : 'relative'} overflow-hidden ${className}`} aria-hidden="true">
      <Image src="/images/sketch/farm-panorama.png" alt="" fill sizes="100vw" className={`object-cover ${imgClassName}`} />
    </div>
  )
}
