/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    orders: Order;
    offers: Offer;
    coupons: Coupon;
    leads: Lead;
    'service-areas': ServiceArea;
    testimonials: Testimonial;
    breeds: Breed;
    departments: Department;
    facilities: Facility;
    posts: Post;
    ticker: Ticker;
    faqs: Faq;
    'legal-pages': LegalPage;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'service-areas': ServiceAreasSelect<false> | ServiceAreasSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    breeds: BreedsSelect<false> | BreedsSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    facilities: FacilitiesSelect<false> | FacilitiesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    ticker: TickerSelect<false> | TickerSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'hi') | ('en' | 'hi')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'hi';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Tip: to change many prices at once, open "₹ Price list" in the menu. For sale prices use Offers; for discount codes use Coupons.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Shown under the name. Write it in the other language, as on the packaging (English page → "देसी गाय का बिलोना घी").
   */
  secondaryName?: string | null;
  /**
   * One or two lines for product cards and search results.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * First image is the main packshot (1:1, cream background).
   */
  images?: (number | Media)[] | null;
  /**
   * Pack sizes. Prices are in rupees, GST-inclusive.
   */
  variants?:
    | {
        label: string;
        sku: string;
        weightGrams?: number | null;
        /**
         * Selling price (₹)
         */
        price?: number | null;
        /**
         * MRP (₹), optional
         */
        mrp?: number | null;
        /**
         * e.g. ₹350 / 100 g
         */
        unitPriceLabel?: string | null;
        inStock?: boolean | null;
        /**
         * Bulk / made to order: shows "Request bulk order" instead of Add to cart.
         */
        onDemand?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Offer daily subscription (milk, curd, buttermilk).
   */
  subscribable?: boolean | null;
  /**
   * Product with no background. Used for the floating product on banners and story slides.
   */
  cutout?: (number | null) | Media;
  /**
   * Optional second photo shown when a shopper hovers the product card. If empty, a details card is shown instead.
   */
  hoverImage?: (number | null) | Media;
  /**
   * Short points on the back of the product card, e.g. "Hand-churned Bilona".
   */
  cardPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Round icon badges shown under the product name.
   */
  badges?:
    | (
        | 'bilona'
        | 'desi-cow'
        | 'makkhan'
        | 'glass'
        | 'clay'
        | 'small-batch'
        | 'no-additives'
        | 'fresh'
        | 'ships'
        | 'rajasthani'
      )[]
    | null;
  /**
   * Designed slides added to the product picture slider.
   */
  storySlides?: ('bilona' | 'process' | 'compare' | 'source' | 'uses')[] | null;
  comparison?:
    | {
        ours: string;
        regular: string;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  ingredients?: string | null;
  shelfLife?: string | null;
  storage?: string | null;
  usage?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Keep these factual (taste, process, packing). Avoid medical claims.
   */
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as an accordion and as FAQPage structured data.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'coming_soon' | 'out_of_stock';
  /**
   * Fresh items can only be delivered in live service areas.
   */
  fulfilment: 'local' | 'ship';
  category: number | Category;
  badge?: ('bestseller' | 'new') | null;
  /**
   * Show in Bestsellers on the home page.
   */
  featured?: boolean | null;
  order?: number | null;
  relatedProducts?: (number | Product)[] | null;
  /**
   * Used in the URL. Lowercase English words separated by hyphens.
   */
  slug: string;
  meta?: {
    /**
     * Search result title (≤ 60 characters). Leave empty to use the default.
     */
    title?: string | null;
    /**
     * Search result description (≤ 155 characters).
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and Google, e.g. "Amrit Bilona ghee in a 1 kg glass jar".
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Small line shown with the title, usually in the other language (e.g. "डेयरी उत्पाद").
   */
  secondaryTitle?: string | null;
  intro?: string | null;
  /**
   * Big line on the collection banner, e.g. "Churned from curd. Cooked slow."
   */
  tagline?: string | null;
  /**
   * Short feature pills on the banner.
   */
  pills?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Transparent product image (PNG) that floats on the banner.
   */
  bannerImage?: (number | null) | Media;
  image?: (number | null) | Media;
  order?: number | null;
  /**
   * Shown as an accordion and as FAQPage structured data.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used in the URL. Lowercase English words separated by hyphens.
   */
  slug: string;
  meta?: {
    /**
     * Search result title (≤ 60 characters). Leave empty to use the default.
     */
    title?: string | null;
    /**
     * Search result description (≤ 155 characters).
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  status: 'pending' | 'confirmed' | 'packed' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  paymentStatus: 'unpaid' | 'paid' | 'failed' | 'refunded';
  paymentMethod?: ('razorpay' | 'whatsapp') | null;
  deliveryType?: ('local' | 'ship') | null;
  items: {
    product?: (number | null) | Product;
    title?: string | null;
    variant?: string | null;
    sku?: string | null;
    quantity?: number | null;
    unitPrice?: number | null;
    lineTotal?: number | null;
    id?: string | null;
  }[];
  subtotal?: number | null;
  /**
   * Coupon discount (₹)
   */
  discount?: number | null;
  deliveryFee?: number | null;
  total: number;
  customer: {
    name: string;
    phone: string;
    email?: string | null;
    address: string;
    landmark?: string | null;
    city?: string | null;
    state?: string | null;
    pincode: string;
    notes?: string | null;
  };
  contactName?: string | null;
  phone?: string | null;
  email?: string | null;
  razorpay?: {
    orderId?: string | null;
    paymentId?: string | null;
  };
  couponCode?: string | null;
  locale?: string | null;
  accessToken?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sale prices applied automatically on the website, e.g. "10% off all ghee this Diwali". If two offers match a product, the bigger discount is used. Changes show on the site within 5 minutes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  /**
   * For your reference, e.g. "Diwali ghee offer".
   */
  title: string;
  /**
   * Short label on the product, e.g. "Diwali offer". Leave empty to use the title.
   */
  badge?: string | null;
  discountType: 'percent' | 'flat';
  /**
   * e.g. 10 for 10% or ₹10
   */
  value: number;
  appliesTo: 'all' | 'categories' | 'products';
  categories?: (number | Category)[] | null;
  products?: (number | Product)[] | null;
  /**
   * Untick to pause the offer.
   */
  active?: boolean | null;
  /**
   * Optional. Empty = starts now.
   */
  startsAt?: string | null;
  /**
   * Optional. Empty = no end.
   */
  endsAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Discount codes for checkout, e.g. WELCOME10. Codes are not case-sensitive.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  /**
   * Letters and numbers, e.g. GHEE100. Saved in capitals.
   */
  code: string;
  /**
   * Shown to the customer when the code works, e.g. "₹100 off your first ghee order".
   */
  description?: string | null;
  type: 'percent' | 'flat' | 'free_delivery';
  /**
   * e.g. 10 for 10% or 100 for ₹100
   */
  value?: number | null;
  /**
   * Minimum order (₹), optional
   */
  minOrder?: number | null;
  /**
   * Cap on the discount (₹), optional
   */
  maxDiscount?: number | null;
  /**
   * The discount is worked out on the matching items only.
   */
  appliesTo: 'all' | 'categories' | 'products';
  categories?: (number | Category)[] | null;
  products?: (number | Product)[] | null;
  /**
   * Total uses allowed, optional
   */
  usageLimit?: number | null;
  /**
   * Uses per phone number, optional (1 = once each)
   */
  perCustomerLimit?: number | null;
  /**
   * Untick to stop the code working.
   */
  active?: boolean | null;
  startsAt?: string | null;
  endsAt?: string | null;
  /**
   * Orders placed with this code (not counting cancelled ones).
   */
  usedCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form, bulk orders, subscriptions, cow enquiries and "Notify me" requests.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  type: 'contact' | 'bulk' | 'subscription' | 'cow' | 'notify' | 'waitlist';
  status?: ('new' | 'contacted' | 'converted' | 'closed') | null;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  pincode?: string | null;
  product?: string | null;
  quantity?: string | null;
  message?: string | null;
  locale?: string | null;
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Where fresh products (milk, dahi, paneer) are delivered. Add an area here to launch it; no code changes needed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas".
 */
export interface ServiceArea {
  id: number;
  name: string;
  city: string;
  /**
   * Comma-separated, e.g. 131001, 131023
   */
  pincodes: string;
  status: 'live' | 'coming_soon';
  /**
   * e.g. Every morning, 6–8 AM
   */
  slot?: string | null;
  /**
   * Unique text for this area page (important for local SEO).
   */
  intro?: string | null;
  landmarks?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as an accordion and as FAQPage structured data.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used in the URL. Lowercase English words separated by hyphens.
   */
  slug: string;
  meta?: {
    /**
     * Search result title (≤ 60 characters). Leave empty to use the default.
     */
    title?: string | null;
    /**
     * Search result description (≤ 155 characters).
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Only real customers. The home page shows reviews once at least 3 are approved.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  locality?: string | null;
  rating?: number | null;
  quote: string;
  product?: (number | null) | Product;
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breeds".
 */
export interface Breed {
  id: number;
  name: string;
  image?: (number | null) | Media;
  onFarm?: boolean | null;
  /**
   * Home region, e.g. "Saurashtra, Gujarat"
   */
  origin?: string | null;
  summary?: string | null;
  traits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  /**
   * Used in the URL. Lowercase English words separated by hyphens.
   */
  slug: string;
  meta?: {
    /**
     * Search result title (≤ 60 characters). Leave empty to use the default.
     */
    title?: string | null;
    /**
     * Search result description (≤ 155 characters).
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  title: string;
  summary: string;
  icon?: ('cow' | 'milk' | 'ghee' | 'jar' | 'lab' | 'box' | 'truck' | 'support' | 'leaf' | 'cold') | null;
  image?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  responsibilities?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  standards?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  head?: {
    name?: string | null;
    role?: string | null;
    photo?: (number | null) | Media;
  };
  relatedProducts?: (number | Product)[] | null;
  /**
   * Shown as an accordion and as FAQPage structured data.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  /**
   * Used in the URL. Lowercase English words separated by hyphens.
   */
  slug: string;
  meta?: {
    /**
     * Search result title (≤ 60 characters). Leave empty to use the default.
     */
    title?: string | null;
    /**
     * Search result description (≤ 155 characters).
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities".
 */
export interface Facility {
  id: number;
  title: string;
  summary: string;
  icon?: ('cow' | 'milk' | 'ghee' | 'jar' | 'lab' | 'box' | 'truck' | 'support' | 'leaf' | 'cold') | null;
  image?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  steps?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  hygiene?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Only verified numbers, e.g. "Cows housed: 250".
   */
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  department?: (number | null) | Department;
  relatedProducts?: (number | Product)[] | null;
  /**
   * Shown as an accordion and as FAQPage structured data.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  /**
   * Used in the URL. Lowercase English words separated by hyphens.
   */
  slug: string;
  meta?: {
    /**
     * Search result title (≤ 60 characters). Leave empty to use the default.
     */
    title?: string | null;
    /**
     * Search result description (≤ 155 characters).
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  excerpt: string;
  cover?: (number | null) | Media;
  category: 'ghee' | 'cows' | 'health' | 'recipes' | 'farm' | 'news';
  tldr?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  keyTakeaways?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as an accordion and as FAQPage structured data.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  sources?:
    | {
        label: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (number | Product)[] | null;
  author?: {
    name?: string | null;
    role?: string | null;
  };
  publishedAt: string;
  /**
   * Used in the URL. Lowercase English words separated by hyphens.
   */
  slug: string;
  meta?: {
    /**
     * Search result title (≤ 60 characters). Leave empty to use the default.
     */
    title?: string | null;
    /**
     * Search result description (≤ 155 characters).
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Short announcements shown in the scrolling bar at the top of every page and on /news.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticker".
 */
export interface Ticker {
  id: number;
  text: string;
  /**
   * Optional longer text for the /news page.
   */
  details?: string | null;
  /**
   * Optional, e.g. /products/desi-cow-golden-ghee
   */
  link?: string | null;
  type?: ('offer' | 'area' | 'launch' | 'event' | 'notice') | null;
  active?: boolean | null;
  /**
   * Higher shows first.
   */
  priority?: number | null;
  startAt?: string | null;
  endAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  topic?: ('general' | 'delivery' | 'payment' | 'products' | 'subscription') | null;
  showOnHome?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  effectiveDate: string;
  order?: number | null;
  /**
   * Used in the URL. Lowercase English words separated by hyphens.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'manager' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'service-areas';
        value: number | ServiceArea;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'breeds';
        value: number | Breed;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'facilities';
        value: number | Facility;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'ticker';
        value: number | Ticker;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  secondaryName?: T;
  shortDescription?: T;
  description?: T;
  images?: T;
  variants?:
    | T
    | {
        label?: T;
        sku?: T;
        weightGrams?: T;
        price?: T;
        mrp?: T;
        unitPriceLabel?: T;
        inStock?: T;
        onDemand?: T;
        id?: T;
      };
  subscribable?: T;
  cutout?: T;
  hoverImage?: T;
  cardPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  badges?: T;
  storySlides?: T;
  comparison?:
    | T
    | {
        ours?: T;
        regular?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  process?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  ingredients?: T;
  shelfLife?: T;
  storage?: T;
  usage?:
    | T
    | {
        text?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  status?: T;
  fulfilment?: T;
  category?: T;
  badge?: T;
  featured?: T;
  order?: T;
  relatedProducts?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  secondaryTitle?: T;
  intro?: T;
  tagline?: T;
  pills?:
    | T
    | {
        text?: T;
        id?: T;
      };
  bannerImage?: T;
  image?: T;
  order?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  deliveryType?: T;
  items?:
    | T
    | {
        product?: T;
        title?: T;
        variant?: T;
        sku?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  subtotal?: T;
  discount?: T;
  deliveryFee?: T;
  total?: T;
  customer?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        address?: T;
        landmark?: T;
        city?: T;
        state?: T;
        pincode?: T;
        notes?: T;
      };
  contactName?: T;
  phone?: T;
  email?: T;
  razorpay?:
    | T
    | {
        orderId?: T;
        paymentId?: T;
      };
  couponCode?: T;
  locale?: T;
  accessToken?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  badge?: T;
  discountType?: T;
  value?: T;
  appliesTo?: T;
  categories?: T;
  products?: T;
  active?: T;
  startsAt?: T;
  endsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  description?: T;
  type?: T;
  value?: T;
  minOrder?: T;
  maxDiscount?: T;
  appliesTo?: T;
  categories?: T;
  products?: T;
  usageLimit?: T;
  perCustomerLimit?: T;
  active?: T;
  startsAt?: T;
  endsAt?: T;
  usedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  name?: T;
  phone?: T;
  email?: T;
  pincode?: T;
  product?: T;
  quantity?: T;
  message?: T;
  locale?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas_select".
 */
export interface ServiceAreasSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  pincodes?: T;
  status?: T;
  slot?: T;
  intro?: T;
  landmarks?:
    | T
    | {
        name?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  locality?: T;
  rating?: T;
  quote?: T;
  product?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breeds_select".
 */
export interface BreedsSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  onFarm?: T;
  origin?: T;
  summary?: T;
  traits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  icon?: T;
  image?: T;
  description?: T;
  responsibilities?:
    | T
    | {
        text?: T;
        id?: T;
      };
  standards?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  head?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
      };
  relatedProducts?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  order?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities_select".
 */
export interface FacilitiesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  icon?: T;
  image?: T;
  gallery?: T;
  description?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  hygiene?:
    | T
    | {
        text?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  department?: T;
  relatedProducts?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  order?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  category?: T;
  tldr?:
    | T
    | {
        text?: T;
        id?: T;
      };
  content?: T;
  keyTakeaways?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  relatedProducts?: T;
  author?:
    | T
    | {
        name?: T;
        role?: T;
      };
  publishedAt?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticker_select".
 */
export interface TickerSelect<T extends boolean = true> {
  text?: T;
  details?: T;
  link?: T;
  type?: T;
  active?: T;
  priority?: T;
  startAt?: T;
  endAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  topic?: T;
  showOnHome?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  effectiveDate?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  ordersPhone: string;
  cowPhone: string;
  email: string;
  address: string;
  mapsUrl?: string | null;
  gstin?: string | null;
  fssai?: string | null;
  udyam?: string | null;
  /**
   * Name shown on the grievance redressal page (E-Commerce Rules 2020).
   */
  grievanceOfficer?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  /**
   * ₹. Orders at or above this ship free.
   */
  freeDeliveryThreshold?: number | null;
  /**
   * ₹ fee for local delivery below the threshold.
   */
  localDeliveryFee?: number | null;
  /**
   * ₹ courier fee below the threshold.
   */
  shippingFee?: number | null;
  /**
   * Order before this time for next-morning delivery.
   */
  cutoffTime?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  ordersPhone?: T;
  cowPhone?: T;
  email?: T;
  address?: T;
  mapsUrl?: T;
  gstin?: T;
  fssai?: T;
  udyam?: T;
  grievanceOfficer?: T;
  facebook?: T;
  instagram?: T;
  youtube?: T;
  freeDeliveryThreshold?: T;
  localDeliveryFee?: T;
  shippingFee?: T;
  cutoffTime?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}